BASE  <https://wiedzmin.fandom.com/wiki/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?who ?whom
WHERE {
    ?whom foaf:knows [ a rdf:Bag; rdfs:member ?who ]
}


SELECT ?who ?whom
       WHERE {
             ?who foaf:knows ?whom
             }