BASE  <https://wiedzmin.fandom.com/wiki/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
    ?o1 foaf:like  ?o2 .
}
WHERE {
    ?o2 foaf:knows ?o1
}



CONSTRUCT {
          ?o1 fhkb:respect  ?o2 .
          }
WHERE {
      ?o2 fhkb:mentoredBy ?o1
      }
